FROM registry.access.redhat.com/ubi8/ubi

ENV NODE_VERSION=14 \
    YARN_VERSION=1.22.10 \
    SONAR_USER_HOME=/opt/sonar/.sonar \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/opt/sonar/bin:/usr/local/kubebuilder/bin

COPY build/* /usr/local/bin/

RUN setup-base.sh
RUN setup-tree.sh
RUN setup-jq.sh
RUN setup-docker-cli.sh
RUN setup-oc.sh
RUN setup-build-harness.sh
RUN setup-sonar.sh
RUN setup-node.sh
