FROM registry.access.redhat.com/ubi8/ubi

ENV GOPATH=/go \
    GOVERSION=1.13.10 \
    GOOS=linux \
    GOARCH=amd64 \
    GOPROXY=direct \
    GOSUMDB=off \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/opt/sonar/bin

COPY build/setup-go.sh /

RUN /setup-go.sh
